platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

def helper_pods
  pod 'SwiftLint', '~> 0.25'
end

def test_pods
  pod 'Nimble-Snapshots', '~> 6.3.0'
  pod 'Nimble', '~> 7.0.3'
  pod 'Quick', '~> 1.2.0'
end

target 'Pastel_Example' do
  pod 'Pastel', :path => '../'

  target 'Pastel_Tests' do
    inherit! :search_paths
    test_pods
  end
end
