platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

def test_pods
  pod 'FBSnapshotTestCase', '~> 2.1.4'
  pod 'Nimble-Snapshots', '~> 6.8.1'
  pod 'Nimble', '~> 7.3.1'
  pod 'Quick', '~> 1.3.2'

end

target 'Pastel_Example' do
  pod 'Pastel', :path => '../'

  target 'Pastel_Tests' do
    inherit! :search_paths
    test_pods

  end
end
